name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR can be auto-merged
        run: |
          if [[ "${{ github.event.pull_request.labels }}" == *"auto-merge"* ]]; then
            # Check if CI checks are successful (replace with your CI check name)
            if [[ "${{ github.event.pull_request.statuses }}" == *"Your-CI-Check-Success"* ]]; then
              # Merge the PR
              echo "Merging PR..."
              gh pr merge --auto
            fi 
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}